# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe63e7f85086b29941bb6519bf79001a6f4f38eb9ac7c7f0471f15a8fa0b65c3b3925246a7dadc058990c8bb29887df11b152690dbcd527143faf4d8010c7914

test:
  secret_key_base: b391dd48c23edde1f7c8aa7152a4a16faf12fdb88e1588e6cd761bda95e582c32ef95cb7e7bf02d6b6cdab3a07ff6c93597d7ed659b278693bd1a978c1b8fa42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
